"""Storage interface. The engine only ever talks to this, never to a database client."""

from __future__ import annotations

from typing import Protocol

from app.engine.models import Followup, Report, Session


class Store(Protocol):
    async def create_session(self, session: Session) -> None: ...
    async def get_session(self, session_id: str) -> Session | None: ...
    async def save_session(self, session: Session) -> None: ...
    async def purge_expired_sessions(self) -> int: ...

    async def create_report(self, report: Report) -> None: ...
    async def save_report(self, report: Report) -> None: ...
    async def get_report(self, report_id: str) -> Report | None: ...
    async def get_report_by_ref(self, ref_code_hmac: str) -> Report | None: ...
    async def list_reports(self) -> list[Report]: ...
    async def find_recent_duplicate(
        self, dedupe_key: str, hospital_id: str | None, category: str
    ) -> bool: ...

    async def add_followup(self, followup: Followup) -> None: ...
